#!/bin/bash
#BSUB -J test_demo
#BSUB -P acc_asthma-allergy
#BSUB -q express
#BSUB -n 3
#BSUB -R span[hosts=1]
#BSUB -R rusage[mem=5000]
#BSUB -W 1:00
#BSUB -o %J.stdout
#BSUB -eo %J.stderr
#BSUB -L /bin/bash


cd  /sc/arion/projects/asthma-allergy/SunBEAM_Whole_genome_Metagenomics/stability-driven-biomarker-ml

module purge
ml  miniforge3
conda activate  /sc/arion/scratch/zhangl26/conda_envs/biomarkerML

python  scripts/run_breast_cancer_demo.py
